### ISSUE TITLE
Explanation of units in Tensormol 0.1 publication...

### ISSUE THREAD

**Issue by Jussmith01** [jparkhill/TensorMol#25]
We've noticed a few issues with units on errors in the Tensormol paper, which is making it hard to compare results. Can you provide (or point to them in the code) the equations used to compute the energy, force, and dipole errors? Our primary confusion is where the per atom part of the equation comes in. From your cost function it appears to be inside the squared part. Is this true from the reported errors? Thanks so much!

**Comment by kunkinger** [comment]
Hi Justin,

If you go to line 4881,  4891 and 4893 in  TFNetworks/TFMolInstanceDirect.py,
you can see "natom" in those lines.  The "natom" is actually the 1/(number
of atoms in each molecule) as you can see from line 1902 or line 1936 in
Containers/TensorMolData.py

As you can see from the code, the denominator is inside the squared part.
Sorry for the confusion caused by the naming.

-Best,
Kun

**Comment by jparkhill** [comment]
Justin- 
Hope all's well down there. Units are def awk af although I wouldn't call it an _issue_.
 
- Energies are Hartree. 
- Forces are in Joules/Angstrom, converted from Hartree/Ang in TFMolManage after the instance.evaluate. 
- Dipoles come out in atomic units, but were converted to the Debye reported in the paper (not within the package -- I just had Kun Check) 

We're just simple men of simple pleasures, and quite certain the ANI networks are more throughly trained, on more data and welcome any reports that your charges/dipoles are more accurate. I would add that our published networks are under-trained simply because we just didn't even feel like waiting longer. The longer this field can avoid becoming a pissing match the better...

Best- 
John

**Comment by Dom1L** [comment]
I need to chime into this one...

I think the forces are actually in J mol-1 A-1.
The conversion factor `JOULEPERHARTREE` that is defined in TensorMol/PhysicalData.py is the conversion factor from Hartree to J/mol and not Hartree to Joule.
