### ISSUE TITLE
Clean up /networks. 

### ISSUE THREAD

**Issue by jparkhill** [jparkhill/TensorMol#7]
Whatever nicotine stuff is in there has to go, and we need to put in some "example networks"

**Comment by jeherr** [comment]
Nicotine stuff removed. @kunkinger can you add a sample network in here?

**Comment by theavey** [comment]
On a related note, the file `networks.tar.gz` linked [here](https://drive.google.com/drive/folders/1IfWPs7i5kfmErIRyuhGv95dSVtNFo0e_) is not actually zipped; it's just a tar archive, so the `.gz` extension is confusing.

Also, trying to unarchive that folder brings up some issues because some of the file/folder names are too long for some file systems to handle.
